apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: site
          image: fabricioveronez/web-page:blue
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      protocol: TCP
